### ISSUE TITLE
Error: command failed

### ISSUE THREAD

**Issue by CameronGo** [blzjns/vscode-raml#7]
I updated my extension to test the fix from https://github.com/blzjns/vscode-raml/issues/3

But I am now getting a different error:
Error: Command Failed: raml2html --template XXXX\.vscode\extensions\blzjns.vscode-raml-3.0.1\raml2html_template/dark.nunjucks XXX\api.raml

From the other comments, I've already installed npm and raml2html manually and, because my raml is still 0.8, I have raml2html v 3.0.1 installed.

When I run the raml2html command referenced in the error manually from a command line, the command is successful and I can redirect that output to an html file and open the resulting html file without an issue.

**Comment by jeremybrochard** [comment]
Hi, it seems that the command is wrong :

> XXXX.vscode\extensions\blzjns.vscode-raml-3.0.1\raml2html_template/dark.nunjucks

There is a problem with the slash at the end, this should be a backslash.

This one should be better : 

> XXXX.vscode\extensions\blzjns.vscode-raml-3.0.1\raml2html_template\dark.nunjucks

**Comment by jasonhebert** [comment]
I am also getting the following error when trying to preview a RAML file:

`Error: Command failed: raml2html --template C:\Users\XXXXX\.vscode\extensions\blzjns.vscode-raml-3.0.1\raml2html_template/dark.nunjucks d:\dev\newRamlProject\api.raml
template not found: C:\Users\XXXXX\.vscode\extensions\blzjns.vscode-raml-3.0.1\raml2html_template/dark.nunjucks`

I edited the plugin code to use the backslash as suggested in previous comment by @jeremybrochard but got the same results so I changed back.

I am using VSCode version 1.11.1 and raml2html version 6.1.0.

**Comment by bddenhartog** [comment]
quote @jasonhebert:

> After further investigation setting different locations for the included template files, raml2html may not have access to the files in the user profile. I've moved the template files included with the plugin to different locations in my filesystem and those located outside the user profile work.

It's odd - It seems that the command **does execute successfully** if I am inside of my `C:\` root, or anywhere in the path along to the extension's directory in `C:\Users\My-Name\.vscode\extensions\`. As soon as I drop into another directory inside `C:\`, however (e.g. `C:\Program Files\`), the command fails. This would seem to be an issue with `raml2html` itself -- I've filed an issue at raml2html/raml2html#343.

**Comment by bddenhartog** [comment]
The issue with `raml2html` has been resolved in raml2html/raml2html#efad9a4, which has been tagged as version `6.2.0` and published to NPM's registry. 

Please make sure you use `yarn` or `npm` to update your installed version of `raml2html` to `6.2.0`.

@CameronGo, please close this issue.

**Comment by luongto** [comment]
I am using Visual Studio Code 1.15.1 and RAML 3.0.1, still get the same issue. "Error: Command failed: raml2html --version"

**Comment by rskokan** [comment]
Same issue.
Error: Command failed: raml2html --template C:\Users\xxx\.vscode\extensions\blzjns.vscode-raml-3.0.1\raml2html_template/dark.nunjucks c:\Users\xxx\test.raml

When I type the command directly in command prompt, it works fine and it generates correct HTML from the RAML file. So this plugin seems don't understands raml2html output/result code.

- blzjns.vscode-raml 3.0.1
- raml2html 3.0.1 (I need it for RAML 0.8)

**Comment by bddenhartog** [comment]
As indicated above, the issue with the `raml2html` executable has nothing to do with `vscode-raml`. Please file an issue for [raml2html/raml2html](https://github.com/raml2html/raml2html) at the project page.

**Comment by rskokan** [comment]
Sorry, missed the comment above.
As I need to use raml2html@3.0.1 for RAML 0.8, I created a quick&dirty fix at https://github.com/rskokan/raml2html/tree/3.0.1.rsk and all if fine now.

**Comment by CameronGo** [comment]
As mentioned above, the issue is in raml2html, so closing this issue.  Since the v3 of raml2html isn't being fixed and it is the only version that supports RAML 0.8, I'm planning to prob look into the OpenAPI (Swagger) spec rather than spend time updating my RAML project to a later version.
